version: "3.3"
services:
  coturn:
    image: michaelfig/coturns
    network_mode: "host"
    environment:
     - AUTH_SECRET=exampleTURNpass
     - AUTH_REALM=example.ru
     - EXTERNAL_IP=1.1.1.1
     - TLS_DIRECTORY=/certs
    volumes:
      - ./certs:/certs:ro
      - ./certs/cert.pem:/certs/tls.crt:ro
      - ./certs/key.pem:/certs/tls.key:ro
      - ./configs/coturn/turnserver.conf.in:/turnserver.conf.in:ro
